# Generated by Django 4.0.3 on 2022-03-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('dexid', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
    ]
