# Generated by Django 4.0.3 on 2022-03-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dexid', models.IntegerField()),
                ('url', models.URLField()),
                ('species', models.CharField(max_length=20)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('images', models.JSONField()),
                ('types', models.CharField(max_length=10)),
                ('abilities', models.CharField(max_length=25)),
            ],
        ),
    ]
