# Generated by Django 4.0.3 on 2022-03-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POKEDEX', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Typing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=10)),
                ('immunities', models.CharField(max_length=10)),
                ('weaknesses', models.CharField(max_length=10)),
                ('strengths', models.CharField(max_length=10)),
            ],
        ),
    ]
