# Generated by Django 4.0.3 on 2022-03-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POKEDEX', '0002_typing_species_type1_species_type2'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='sprite',
            field=models.URLField(default='x.com'),
            preserve_default=False,
        ),
    ]
