# Generated by Django 4.0.3 on 2022-03-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POKEDEX', '0002_ability_typing'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='url',
            field=models.URLField(default='#'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typing',
            name='url',
            field=models.URLField(default='#'),
            preserve_default=False,
        ),
    ]
