# Generated by Django 4.0.3 on 2022-03-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POKEDEX', '0003_ability_url_typing_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='abilities',
            new_name='ability1',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='types',
            new_name='type1',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='height',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='weight',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability2',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='hidden_ability',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='stats',
            field=models.JSONField(default={'height': 0, 'weight': 0}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
