# Generated by Django 4.0.3 on 2022-03-06 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POKEDEX', '0004_rename_abilities_pokemon_ability1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='url',
        ),
    ]
