# Generated by Django 4.0.3 on 2022-03-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POKEDEX', '0005_remove_pokemon_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name': 'Pokemon', 'verbose_name_plural': 'Pokemon'},
        ),
        migrations.RemoveField(
            model_name='ability',
            name='url',
        ),
        migrations.RemoveField(
            model_name='typing',
            name='url',
        ),
    ]
