# Generated by Django 4.0.3 on 2022-03-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POKEDEX', '0006_alter_pokemon_options_remove_ability_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typing',
            name='typeid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
