# Generated by Django 4.0.3 on 2022-03-07 09:23

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POKEDEX', '0006_alter_species_height_alter_species_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='typing',
            name='color',
            field=colorful.fields.RGBColorField(default='#000000'),
        ),
    ]
