# Generated by Django 4.0.3 on 2022-03-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POKEDEX', '0007_typing_typeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='abilityid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
