# Generated by Django 4.0.3 on 2022-03-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POKEDEX', '0008_typing_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='pokemon',
            field=models.ManyToManyField(to='POKEDEX.species'),
        ),
    ]
