# Generated by Django 4.0 on 2022-01-06 01:28

from django.db import migrations, models
import django.db.models.deletion
import pics_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pics_app.models.get_upload_path)),
                ('caption', models.CharField(max_length=5000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='users_app.user')),
            ],
        ),
    ]
