# Generated by Django 4.0.1 on 2022-01-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='public',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
