# Generated by Django 4.0 on 2021-12-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='text',
            field=models.TextField(default='Mow the lawn'),
        ),
    ]
