# Generated by Django 4.0 on 2021-12-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todoitem_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Todo item'),
        ),
    ]
