# Generated by Django 4.0 on 2022-01-19 01:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('h', 'High'), ('m', 'Medium'), ('l', 'Low')], default='m', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mymodel', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False, null=True)),
                ('priority', models.ForeignKey(default="1", blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='todo_list.priority')),
            ],
        ),
    ]
