# Generated by Django 4.0.1 on 2022-03-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='priority',
            field=models.CharField(choices=[('h', 'High'), ('m', 'Medium'), ('l', 'Low')], default='', max_length=30, null=True),
        ),
    ]
