# Generated by Django 4.0.3 on 2022-04-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0002_alter_pokemon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemontype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
