# Generated by Django 3.2.7 on 2022-01-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogit_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
