# Generated by Django 4.0.3 on 2022-03-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='url',
            field=models.CharField(default='blank', max_length=300),
            preserve_default=False,
        ),
    ]
