# Generated by Django 4.0.1 on 2022-01-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
    ]
