# Generated by Django 4.0.1 on 2022-01-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0002_alter_pokemon_height_alter_pokemon_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_back',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_front',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
