# Generated by Django 3.2.7 on 2022-01-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0006_alter_pokemon_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(blank=True, to='pokedex_app.PokemonType'),
        ),
    ]
