# Generated by Django 3.2.7 on 2022-01-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0007_alter_pokemon_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image_front',
            field=models.ImageField(blank=True, upload_to='images_front'),
        ),
    ]
