# Generated by Django 3.2.7 on 2022-01-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0008_alter_pokemon_image_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image_back',
            field=models.ImageField(blank=True, upload_to='images_back/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_front',
            field=models.ImageField(blank=True, upload_to='images_front/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
