# Generated by Django 4.0.2 on 2022-02-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOGS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='BLOGS.Post'),
        ),
    ]
