# Generated by Django 4.0.1 on 2022-01-14 02:48

from django.db import migrations, models
import users_handler.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='blog/static/img/avatars/default_avt.png', upload_to=users_handler.models.upload_path),
        ),
    ]
