# Generated by Django 4.0.1 on 2022-01-28 03:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the key', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='KeyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter what key is used for (e.g. Vehicle, Door , Locker, Padlock)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeyInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular key across whole library', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Key availability', max_length=1)),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.keyid')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='keyid',
            name='usefor',
            field=models.ManyToManyField(help_text='Select what this key is used for', to='catalog.KeyType'),
        ),
    ]
