# Generated by Django 4.0.1 on 2022-01-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyinstance',
            name='imprint',
        ),
        migrations.AlterField(
            model_name='keyinstance',
            name='id',
            field=models.CharField(help_text='Unique ID for this particular key across whole library', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Missing'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Key availability', max_length=1),
        ),
    ]
