# Generated by Django 4.0.1 on 2022-02-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_keyinstance_imprint_alter_keyinstance_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyType',
            new_name='Lock',
        ),
        migrations.AlterField(
            model_name='keyinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Missing'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='a', help_text='Key availability', max_length=1),
        ),
    ]
