# Generated by Django 4.0.1 on 2022-02-02 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_keyinstance_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinstance',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.keyid'),
        ),
        migrations.AlterField(
            model_name='lock',
            name='name',
            field=models.CharField(help_text='What the key is for (e.g. Vehicle, Door , Locker, Padlock)', max_length=50),
        ),
    ]
