# Generated by Django 4.0.1 on 2022-02-03 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_keyinstance_key_alter_lock_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set key as returned'),)},
        ),
    ]
