# Generated by Django 4.0.1 on 2022-02-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_keyinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyinstance',
            options={'ordering': ['due_back']},
        ),
    ]
