# Generated by Django 4.0.1 on 2022-02-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_keyinstance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Missing'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Requested')], default='a', help_text='Key availability', max_length=1),
        ),
    ]
