# Generated by Django 4.0.1 on 2022-01-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
