# Generated by Django 4.0.1 on 2022-01-25 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='key_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=100)),
                ('key_for', models.CharField(max_length=100)),
                ('available_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='key_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='key_issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField()),
                ('user_sign_date', models.DateTimeField()),
                ('return_due_date', models.DateTimeField()),
                ('key_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyz_app.key_list')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyz_app.key_user')),
            ],
        ),
    ]
