# Generated by Django 4.0 on 2021-12-29 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Meidum'), ('L', 'Low')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=200)),
                ('completed_date', models.DateTimeField(auto_now_add=True)),
                ('todo_priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='todo.priority')),
            ],
        ),
    ]
