# Generated by Django 4.0 on 2021-12-30 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='todo_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_priority', to='todo.priority'),
        ),
    ]
