# Generated by Django 4.0.1 on 2022-01-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0002_alter_pokemon_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='url',
            field=models.CharField(default='www.google.com', max_length=300),
            preserve_default=False,
        ),
    ]
