# Generated by Django 4.0.1 on 2022-01-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_priority_alter_todoitem_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
