# Generated by Django 4.0.1 on 2022-01-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_todoitem_completed_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='completed_or_not',
            field=models.BooleanField(default=None),
        ),
    ]
