# Generated by Django 3.2.10 on 2022-03-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priority",
            name="name",
            field=models.CharField(
                choices=[(1, "High"), (2, "Medium"), (3, "Low")],
                default=2,
                max_length=6,
            ),
        ),
    ]
