# Generated by Django 3.2.10 on 2022-01-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_todolist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='color',
            field=models.CharField(default='bg-primary', max_length=250),
        ),
        migrations.AddField(
            model_name='todolist',
            name='icon',
            field=models.CharField(default='fas fa-list', max_length=250),
        ),
    ]
