# Generated by Django 3.2.10 on 2022-03-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0005_alter_priority_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="priority",
            name="name",
            field=models.CharField(
                choices=[(1, 1), (2, 2), (3, 3)], default="Medium", max_length=6
            ),
        ),
    ]
