# Generated by Django 3.2.10 on 2022-03-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0006_alter_priority_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="priority",
            options={"ordering": ["-name"], "verbose_name_plural": "Priorities"},
        ),
        migrations.AlterField(
            model_name="priority",
            name="name",
            field=models.IntegerField(choices=[(1, "Low"), (2, "Medium"), (3, "High")]),
        ),
    ]
