# Generated by Django 4.0 on 2022-03-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_auto_20220306_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['name'], 'verbose_name_plural': 'Priorities'},
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.IntegerField(choices=[(0, 'Completed'), (1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
    ]
