# Generated by Django 3.2.7 on 2022-01-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_todo_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='priority',
        ),
    ]
