# Generated by Django 3.2.7 on 2022-01-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_remove_priority_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='priority',
            field=models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], default='low', max_length=7),
        ),
    ]
